<?php
// $Id: views_slideshow_slider.module,v 1.1.2.1.2.5 2010/02/23 22:21:44 psynaptic Exp $

/**
 * @file
 * Views Slideshow: slider has options for working with node views.
 *
 * The slider mode adds two parts to the view: the first part is a
 * series of items displayed as a list, the second part is either a full node
 * or a node teaser. The slideshow will synchronize the two, so that the
 * 'active' item will correspond to the single full/teaser item. The slide show
 * can be set to advance automatically or on mouse hover/click.
 */


/**
 * Implements hook_theme().
 */
function views_slideshow_slider_theme($existing, $type, $theme, $path) {
  return array(
    'views_slideshow_slider' => array(
      'arguments' => array('view' => NULL, 'options' => array(), 'rows' => array(), 'title' => ''),
      'template' => 'views-slideshow-slider',
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_controls' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_control_previous' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_control_pause' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_control_next' =>array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_pager' => array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_image_count' => array(
      'arguments' => array('id' => '', 'view' => NULL, 'options' => array()),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_no_display_section' => array(
      'arguments' => array('view' => NULL, 'rows' => NULL, 'id' => NULL, 'mode' => NULL, 'teaser' => TRUE),
      'file' => 'views_slideshow_slider.theme.inc',
    ),    
    'views_slideshow_slider_no_display_teaser' => array(
      'arguments' => array('item' => NULL, 'id' => NULL, 'count' => NULL),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
    'views_slideshow_slider_slider' => array(
      'arguments' => array('id' => NULL),
      'file' => 'views_slideshow_slider.theme.inc',
    ),
  );
}

/**
 * Implements hook_help().
 */
function views_slideshow_slider_help($path, $arg) {
  switch ($path) {
    case 'admin/help#views_slideshow_slider':
      if (module_exists('advanced_help')) {
        $output = '<p>' . l(t('Click here to view the documentation for Views Slideshow slider'),  'admin/advanced_help/views_slideshow_slider') . '</p>';
      }
      else {
        $output = '<p>' . t('Views Slideshow slider help can be found by installing and enabling the !advanced_help.',  array('!advanced_help' => l(t('Advanced Help module'), 'http://drupal.org/project/advanced_help'))) . '</p>';
      }
      return $output;
  }
}
